### ISSUE TITLE
nvidia-smi hangs when devices=2 using spark-submit in yarn

### ISSUE THREAD

**Issue by nhe150** [yahoo/CaffeOnSpark#23]
In single node with 2 gpus, when submit using devices=2. nvidia-smi hang up. Need to shutdown computer to bring nvidia gpu back for use. The operation system is ubuntu 14.04.

**Comment by mriduljain** [comment]
Could you check the logs on the tracker? I am sure the tracker would be responsive

**Comment by nhe150** [comment]
Would you let me know how to check tracker logs?

**Comment by mriduljain** [comment]
Could you access this:
spark://<yourmasterhostname>:7077

**Comment by mriduljain** [comment]
ok it got trimmed..... spark:// < yourmasterhostname > : 7077

**Comment by nhe150** [comment]
Yes, I am using yarn. all executor logs logged something and stopped collecting anything. yarn-application is running for hours without doing anything.

**Comment by nhe150** [comment]
CaffeOnspark works beautifully  with device=1 and across mulitple nodes.

**Comment by junshi15** [comment]
What's your CUDA version? 6.5? 7.0? 7.5?
What's your GPU compute-mode? Default? Exclusive_thread? Exclusive_process?
Did you run other CUDA applications while you were running CaffeOnSpark?
Did CaffeOnSpark run fine with devcies=2 if you don't launch nvidia-smi? meaning somehow nvidia-smi was interfering with CaffeOnSpark?

**Comment by nhe150** [comment]
cuda 7.5.
GPU mode is default.
only running CaffeOnSpark.
without launch nvidia-smi, with devices=2; It hangs.

Here is the printout of nvidia-smi -i 0 -q
==============NVSMI LOG==============

Timestamp                           : Fri Mar 11 10:14:39 2016
Driver Version                      : 352.79

Attached GPUs                       : 2
GPU 0000:06:00.0
    Product Name                    : Tesla K80
    Product Brand                   : Tesla
    Display Mode                    : Disabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 1920
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 0324815008413
    GPU UUID                        : GPU-72f52228-2526-1fb0-d3ba-803d31d75dc6
    Minor Number                    : 0
    VBIOS Version                   : 80.21.1B.00.01
    MultiGPU Board                  : Yes
    Board ID                        : 0x400
    Inforom Version
        Image Version               : 2080.0200.00.04
        OEM Object                  : 1.1
        ECC Object                  : 3.0
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    PCI
        Bus                         : 0x06
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x102D10DE
        Bus Id                      : 0000:06:00.0
        Sub System Id               : 0x106C10DE
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : PLX
            Firmware                : 0xF0472900
        Replays since reset         : 0
        Tx Throughput               : N/A
        Rx Throughput               : N/A
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
        Unknown                     : Not Active
    FB Memory Usage
        Total                       : 11519 MiB
        Used                        : 55 MiB
        Free                        : 11464 MiB
    BAR1 Memory Usage
        Total                       : 16384 MiB
        Used                        : 2 MiB
        Free                        : 16382 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Ecc Mode
        Current                     : Enabled
        Pending                     : Enabled
    ECC Errors
        Volatile
            Single Bit
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : 0
                Total               : 0
            Double Bit
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : 0
                Total               : 0
        Aggregate
            Single Bit
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : 0
                Total               : 0
            Double Bit
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : 0
                L2 Cache            : 0
                Texture Memory      : 0
                Total               : 0
    Retired Pages
        Single Bit ECC              : 0
        Double Bit ECC              : 0
        Pending                     : No
    Temperature
        GPU Current Temp            : 38 C
        GPU Shutdown Temp           : 93 C
        GPU Slowdown Temp           : 88 C
    Power Readings
        Power Management            : Supported
        Power Draw                  : 60.04 W
        Power Limit                 : 149.00 W
        Default Power Limit         : 149.00 W
        Enforced Power Limit        : 149.00 W
        Min Power Limit             : 100.00 W
        Max Power Limit             : 175.00 W
    Clocks
        Graphics                    : 719 MHz
        SM                          : 719 MHz
        Memory                      : 2505 MHz
    Applications Clocks
        Graphics                    : 562 MHz
        Memory                      : 2505 MHz
    Default Applications Clocks
        Graphics                    : 562 MHz
        Memory                      : 2505 MHz
    Max Clocks
        Graphics                    : 875 MHz
        SM                          : 875 MHz
        Memory                      : 2505 MHz
    Clock Policy
        Auto Boost                  : On
        Auto Boost Default          : On
    Processes                       : None

**Comment by mriduljain** [comment]
I will try reproducing it

**Comment by junshi15** [comment]
I did not see a smoking gun in your nvidia-smi logs. We use K80 too, but with cuda 7.0. We set GPU mode to exclusive_process, but I don't expect hang in default mode.

Are you able to run BVLC caffe code with multiple-GPU? The way CaffeOnSpark uses GPU devices is similar to BVLC caffe does.

Do you know where the program was stuck? Was it right after devices were allocated? I guess you are not able to get the yarn log with the computer hung. But if you do have the log, it should reveal a lot of information.

It may require some serious debug to pinpoint the issue, meaning either inserting logs into the code and/or stepping through the code manually.

**Comment by nhe150** [comment]
1) BVLC with multiple GPU is runing fine
2) The node is okay. just GPU kernel all messed up. Here is the logs:
seems the system hangs in 
collect at CaffeOnSpark.scala:125

Yarn logs shows:


Container logs :
16/03/11 13:22:54 INFO storage.BlockManagerMaster: Trying to register BlockManager
16/03/11 13:22:54 INFO storage.BlockManagerMaster: Registered BlockManager
16/03/11 13:22:58 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 1
16/03/11 13:22:58 INFO executor.Executor: Running task 1.0 in stage 0.0 (TID 1)
16/03/11 13:22:58 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 0
16/03/11 13:22:58 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 2.0 KB, free 2.0 KB)
16/03/11 13:22:58 INFO broadcast.TorrentBroadcast: Reading broadcast variable 0 took 121 ms
16/03/11 13:22:58 INFO storage.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 3.1 KB, free 5.2 KB)
16/03/11 13:22:58 INFO caffe.CaffeProcessor: my rank is 1
16/03/11 13:22:58 INFO caffe.LMDB: Batch size:100

driver logs:
16/03/11 13:22:57 INFO cluster.YarnClusterScheduler: Adding task set 0.0 with 2 tasks
16/03/11 13:22:57 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, bdalab12.samsungsdsra.com, partition 0,PROCESS_LOCAL, 1966 bytes)
16/03/11 13:22:57 INFO scheduler.TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, bdalab12.samsungsdsra.com, partition 1,PROCESS_LOCAL, 1966 bytes)
16/03/11 13:22:58 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on bdalab12.samsungsdsra.com:53239 (size: 2.0 KB, free: 511.1 MB)
16/03/11 13:22:58 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on bdalab12.samsungsdsra.com:39282 (size: 2.0 KB, free: 511.1 MB)

3) dmesg shows:
[ 5836.508857] RIP: 0010:[<ffffffffc0f5ab4d>]  [<ffffffffc0f5ab4d>] _nv002815rm+0x51d/0x610 [nvidia]
[ 5836.508858] RSP: 0018:ffff881fba357a68  EFLAGS: 00010246
[ 5836.508858] RAX: 0000000000000000 RBX: ffff881f6d2e4008 RCX: 0000000000000000
[ 5836.508859] RDX: 0000000000000000 RSI: 0000000000000011 RDI: 0000000000000000
[ 5836.508859] RBP: ffff88200ca65f58 R08: 0000000000000202 R09: ffff88200c58c700
[ 5836.508860] R10: 0000000056e33725 R11: ffffffffc137b7f0 R12: 0000000000000000
[ 5836.508860] R13: 0000000000000001 R14: 0000000000000001 R15: ffff88200b87a408
[ 5836.508861] FS:  00007f963825b700(0000) GS:ffff88103f420000(0000) knlGS:0000000000000000
[ 5836.508862] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 5836.508862] CR2: 0000000000000020 CR3: 0000000001c13000 CR4: 00000000001407e0
[ 5836.508863] Stack:
[ 5836.508864]  ffff881f6d2e4008 ffff882027862008 ffff88200c7da808 0000000000000000
[ 5836.508865]  ffff881f6d388008 ffffffffc0f54b50 ffff882027862008 ffff881f6d2e4008
[ 5836.508866]  0000000000001100 0000000000000000 0000000000000024 ffffffffc0f4b881
[ 5836.508866] Call Trace:
[ 5836.508906]  [<ffffffffc0f54b50>] ? _nv003017rm+0xf0/0x1c0 [nvidia]
[ 5836.508944]  [<ffffffffc0f4b881>] ? _nv003008rm+0x11/0x50 [nvidia]
[ 5836.509026]  [<ffffffffc1173a40>] ? _nv002021rm+0x2640/0x3c30 [nvidia]
[ 5836.509061]  [<ffffffffc13c6a69>] ? _nv000654rm+0x2b9/0x340 [nvidia]
[ 5836.509101]  [<ffffffffc13bcf9a>] ? rm_disable_adapter+0x6a/0x130 [nvidia]
[ 5836.509137]  [<ffffffffc13cd526>] ? nvidia_close+0x1a6/0x410 [nvidia]
[ 5836.509173]  [<ffffffffc13cae79>] ? nvidia_frontend_close+0x49/0xa0 [nvidia]
[ 5836.509176]  [<ffffffff811d74b4>] ? __fput+0xe4/0x220
[ 5836.509177]  [<ffffffff811d763e>] ? ____fput+0xe/0x10
[ 5836.509179]  [<ffffffff8108f4dc>] ? task_work_run+0xac/0xd0
[ 5836.509182]  [<ffffffff810713c8>] ? do_exit+0x2b8/0xa60
[ 5836.509184]  [<ffffffff810e4bc2>] ? __unqueue_futex+0x32/0x70
[ 5836.509185]  [<ffffffff810e5be6>] ? futex_wait+0x126/0x290
[ 5836.509187]  [<ffffffff81071bef>] ? do_group_exit+0x3f/0xa0
[ 5836.509188]  [<ffffffff81081790>] ? get_signal_to_deliver+0x1d0/0x6f0
[ 5836.509192]  [<ffffffff81013538>] ? do_signal+0x48/0xad0
[ 5836.509195]  [<ffffffff81219513>] ? ep_poll+0x113/0x340
[ 5836.509196]  [<ffffffff81014029>] ? do_notify_resume+0x69/0xb0
[ 5836.509200]  [<ffffffff81771b8a>] ? int_signal+0x12/0x17
[ 5836.509210] Code: 07 74 00 31 c9 44 89 f2 be 2c 00 00 00 48 89 c7 ff 50 20 48 85 c0 49 89 c4 0f 84 d6 00 00 00 31 c9 31 d2 be 11 00 00 00 4c 89 e7 <41> ff 54 24 20 be 30 00 00 00 48 8b b8 a8 05 00 00 48 89 c3 ff
[ 5836.509248] RIP  [<ffffffffc0f5ab4d>] _nv002815rm+0x51d/0x610 [nvidia]
[ 5836.509248]  RSP <ffff881fba357a68>
[ 5836.509249] CR2: 0000000000000020
[ 5836.526727] ---[ end trace 25db34162ba3477f ]---
[ 5836.551229] Fixing recursive fault but reboot is needed!

**Comment by nhe150** [comment]
NodeManager keep on saying:
2016-03-11 13:53:21,627 INFO org.apache.hadoop.yarn.server.nodemanager.containermanager.monitor.ContainersMonitorImpl: Memory usage of ProcessTree 7412 for container-id container_1457731243663_0001_02_000003: 656.0 MB of 2 GB physical memory used; 4.6 GB of 4.2 GB virtual memory used

**Comment by junshi15** [comment]
Judging from container logs, it probably died at CaffeProcessor initialization, i.e. this line:
https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/CaffeOnSpark.scala#L116
It is likely during GPU device allocation. The devices are obtained by the following code:
https://github.com/yahoo/caffe/blob/master/src/caffe/common.cpp#L204-L223
I don't know why this won't work on your system. 

"Fixing recursive fault but reboot is needed!" sounds like hardware conflict.

**Comment by mriduljain** [comment]
I tried this and works for me. @nhe150 is this consistently happening?

**Comment by mriduljain** [comment]
One of the differences I see on my nodes is that persistence is "Enabled", which keeps the driver loaded and GPUs initialized even when no apps are running.

**Comment by nhe150** [comment]
set persistence to "Enabled" solved the hanging issue. 
Thank @junshi15 and @mriduljain for the help.
